name: "Test: DevBox Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: "true" 
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}      

      - name: Install Dev Center CLI extension
        run: az extension add --name devcenter

      - name: Run Azure
        run: |
          az devcenter dev dev-box create \
          --dev-center-name Meridian-Retail \
          --project-name Retail-Engineering-IT \
          --user-id 950add13-bb00-4335-9d0b-6330861ece19 \
          --pool-name Infosys_Developers \
          --name dev_box_01


    
