name: "Terraform: Force State Refresh"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'non-prod'
        type: choice
        options:
          - non-prod
          - prod
      component:
        description: 'Select component state file'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - rbac
          - network
          - storage
          - workspace


permissions:
  id-token: write
  contents: read

jobs:
  tf_refresh_state:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ format('./main/{0}', inputs.component) }}
    env:
      TF_VAR_environment: ${{ inputs.environment }}
      ARM_USE_OIDC: "true" 
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
  
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}      

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="../../modules/backend/common.tfbackend" \
            -backend-config="container_name=${{ inputs.environment }}" \
            -backend-config="key=${{ inputs.component }}/terraform.tfstate"

      #- name: Refresh Terraform State
      #  run: |
      #    terraform refresh -var-file="../config/${{ inputs.environment }}/${{ inputs.component }}-${{ inputs.environment }}.tfvars" -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -var-file="../config/${{ inputs.environment }}/${{ inputs.component }}-${{ inputs.environment }}.tfvars" -no-color -out=tfplan


    
